name: Sign Decompiled APK

on:
  push:
    paths:
      - '**'  # Trigger on any file changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Install apktool, zipalign, apksigner
      - name: Install apktool and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget zipalign apksigner
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O apktool
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
          chmod +x apktool
          sudo mv apktool apktool.jar /usr/local/bin/

      # 4. Inject raw config.json directly
      - name: Inject config.json
        run: |
          mkdir -p assets/flutter_assets/assets
          cat <<EOF > assets/flutter_assets/assets/config.json
    {
    "version": 1,
    "appID": 1,
    "versionCode": 1,
    "versionName": "1.0.0",

    "package": "com.neshop.android",
    "appTitle": "Rabi SIngh",
    "initialUrl": "https://cv.rabi.info.np",
    "mainSiteDomain": "cv.rabi.info.np",

    "primaryColor": "0xFF6366F1",
    "secondaryColor": "0xFF8B5CF6",
    "textColor": "0xFF1F2937",
    "iconColor": "0xFFFFFFFF",
    "backgroundColor": "0xFFF8FAFC",

    "externalOpen": 1,
    "zoomEnable": 0,
    "showLoader": 1,
    "swipeRefresh": 0,
    "scrollBar": 0,
    "orientation": 1,
    "appLinks": ["neshop.com.np", "partner.neshop.com.np"],
    "urlParam": [
     {
      "param": "inapp",
      "value": "yes"
     }  
    ],

    "cookies": [
     {
      "param": "cookie1",
      "value": "yes"
     } 
    ],

    "idSplash": 1,
    "splashTitle": "Welcome to",
    "splashSubtitle": "Rabii Singhh",
    "splashDescription": "Appvly helps websites reach users with full mobile app experience.",
    "splashDuration": 3,
 
    "idSidebar": 1,
    "navTitle": "Navigation Menu",
    "navIcon": "home",
    "navItems": [
        {
            "name": "Home",
            "url": "https://neshop.com.np",
            "icon": "home"
        },
        {
            "name": "Cart",
            "url": "https://neshop.com.np/cart",
            "icon": "home"
        }
    ],
  
    "idHeader": 1,
    "displayRefresh": 1,
    "displaySearch": 0,
    "searchURL": "https://neshop.com.np/search-results/?keyword=",
    "displayAppBarIcon": 0,
    "appBarIcon": [
        {
        "url": "https://neshop.com.np",
        "icon": "home"
        }
    ],

    "idFooter": 0,
    "footerItems": [
        {
            "name": "Home",
            "url": "https://neshop.com.np",
            "icon": "home"
        },
        {
            "name": "Cart",
            "url": "https://neshop.com.np/cart",
            "icon": "shopping_cart"
        },
        {
            "name": "shopping",
            "url": "https://neshop.com.np/bag",
            "icon": "rate"
        },
        {
            "name": "Account",
            "url": "https://neshop.com.np/user-account",
            "icon": "user"
        }
    ],

    "floatingButton": 1,
    "floatingIcon": "wechat",
    "floatingClick": "https://wa.me/9779804292202"

    }
          EOF

      # 5. Rebuild APK
      - name: Rebuild APK
        run: |
          apktool b . -o unsigned.apk

      # 6. Zipalign
      - name: Zipalign APK
        run: |
          zipalign -p -f 4 unsigned.apk aligned.apk

      # 7. Decode Keystore from base64 secret
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > appvly.jks

      # 8. Sign APK using provided secrets
      - name: Sign APK
        run: |
          apksigner sign \
            --ks appvly.jks \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASS }} \
            --key-pass pass:${{ secrets.KEY_PASS }} \
            --out final.apk \
            aligned.apk

      # 9. Verify signature
      - name: Verify APK Signature
        run: |
          apksigner verify final.apk

      # 10. Upload signed APK
      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: signed_appvly_apk
          path: final.apk
