name: Sign Decompiled APK

on:
  push:
    paths:
      - '**'  # Trigger on any file changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Install apktool, zipalign, apksigner
      - name: Install apktool and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget zipalign apksigner
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O apktool
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar -O apktool.jar
          chmod +x apktool
          sudo mv apktool apktool.jar /usr/local/bin/

      # 4. Inject config.json from inline base64
      - name: Inject config.json
        run: |
          mkdir -p assets/flutter_assets/assets
          echo "ewogICAgInZlcnNpb24iOiAxLAogICAgImFwcElEIjogMSwKICAgICJ2ZXJzaW9uQ29kZSI6IDEsCiAgICAidmVyc2lvbk5hbWUiOiAiMS4wLjAiLAoKICAgICJwYWNrYWdlIjogImNvbS5uZXNob3AuYW5kcm9pZCIsCiAgICAiYXBwVGl0bGUiOiAiUmFiaSBTaW5naCIsCiAgICAiaW5pdGlhbFVybCI6ICJodHRwczovL2N2LnJhYmkuaW5mby5ucCIsCiAgICAibWFpblNpdGVEb21haW4iOiAiY3YucmFiaS5pbmZvLm5wIiwKCiAgICAicHJpbWFyeUNvbG9yIjogIjB4RkY2MzY2RjEiLAogICAgInNlY29uZGFyeUNvbG9yIjogIjB4RkY4QjVDRjYiLAogICAgInRleHRDb2xvciI6ICIweEZGMUYyOTM3IiwKICAgICJpY29uQ29sb3IiOiAiMHhGRkZGRkZGRiIsCiAgICAiYmFja2dyb3VuZENvbG9yIjogIjB4RkZGOEZBRkMiLAoKICAgICJleHRlcm5hbE9wZW4iOiAxLAogICAgInpvb21FbmFibGUiOiAwLAogICAgInNob3dMb2FkZXIiOiAxLAogICAgInN3aXBlUmVmcmVzaCI6IDAsCiAgICAic2Nyb2xsQmFyIjogMCwKICAgICJvcmllbnRhdGlvbiI6IDEsCiAgICAiYXBwTGlua3MiOiBbIm5lc2hvcC5jb20ubnAiLCAicGFydG5lci5uZXNob3AuY29tLm5wIl0sCiAgICAidXJsUGFyYW0iOiBbCiAgICAgewogICAgICAicGFyYW0iOiAiaW5hcHAiLAogICAgICAidmFsdWUiOiAieWVzIgogICAgIH0gIAogICAgXSwKCiAgICAiY29va2llcyI6IFsKICAgICB7CiAgICAgICJwYXJhbSI6ICJjb29raWUxIiwKICAgICAgInZhbHVlIjogInllcyIKICAgICB9IAogICAgXSwKCiAgICAiaWRTcGxhc2giOiAxLAogICAgInNwbGFzaFRpdGxlIjogIldlbGNvbWUgdG8iLAogICAgInNwbGFzaFN1YnRpdGxlIjogIlJhYmlpIFNpbmdoaHMiLAogICAgInNwbGFzaERlc2NyaXB0aW9uIjogIkFwcHZseSBoZWxwcyB3ZWJzaXRlcyByZWFjaCB1c2VycyB3aXRoIGZ1bGwgbW9iaWxlIGFwcCBleHBlcmllbmNlLiIsCiAgICAic3BsYXNoRHVyYXRpb24iOiAzLAogCiAgICAiaWRTaWRlYmFyIjogMSwKICAgICJuYXZUaXRsZSI6ICJOYXZpZ2F0aW9uIE1lbnUiLAogICAgIm5hdkljb24iOiAiaG9tZSIsCiAgICAibmF2SXRlbXMiOiBbCiAgICAgICAgewogICAgICAgICAgICAibmFtZSI6ICJIb21lIiwKICAgICAgICAgICAgInVybCI6ICJodHRwczovL25lc2hvcC5jb20ubnAiLAogICAgICAgICAgICAiaWNvbiI6ICJob21lIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAibmFtZSI6ICJDYXJ0IiwKICAgICAgICAgICAgInVybCI6ICJodHRwczovL25lc2hvcC5jb20ubnAvY2FydCIsCiAgICAgICAgICAgICJpY29uIjogImhvbWUiCiAgICAgICAgfQogICAgXSwKICAKICAgICJpZEhlYWRlciI6IDEsCiAgICAiZGlzcGxheVJlZnJlc2giOiAxLAogICAgImRpc3BsYXlTZWFyY2giOiAwLAogICAgInNlYXJjaFVSTCI6ICJodHRwczovL25lc2hvcC5jb20ubnAvc2VhcmNoLXJlc3VsdHMvP2tleXdvcmQ9IiwKICAgICJkaXNwbGF5QXBwQmFySWNvbiI6IDAsCiAgICAiYXBwQmFySWNvbiI6IFsKICAgICAgICB7CiAgICAgICAgInVybCI6ICJodHRwczovL25lc2hvcC5jb20ubnAiLAogICAgICAgICJpY29uIjogImhvbWUiCiAgICAgICAgfQogICAgXSwKCiAgICAiaWRGb290ZXIiOiAwLAogICAgImZvb3Rlckl0ZW1zIjogWwogICAgICAgIHsKICAgICAgICAgICAgIm5hbWUiOiAiSG9tZSIsCiAgICAgICAgICAgICJ1cmwiOiAiaHR0cHM6Ly9uZXNob3AuY29tLm5wIiwKICAgICAgICAgICAgImljb24iOiAiaG9tZSIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgIm5hbWUiOiAiQ2FydCIsCiAgICAgICAgICAgICJ1cmwiOiAiaHR0cHM6Ly9uZXNob3AuY29tLm5wL2NhcnQiLAogICAgICAgICAgICAiaWNvbiI6ICJzaG9wcGluZ19jYXJ0IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAibmFtZSI6ICJzaG9wcGluZyIsCiAgICAgICAgICAgICJ1cmwiOiAiaHR0cHM6Ly9uZXNob3AuY29tLm5wL2JhZyIsCiAgICAgICAgICAgICJpY29uIjogInJhdGUiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJuYW1lIjogIkFjY291bnQiLAogICAgICAgICAgICAidXJsIjogImh0dHBzOi8vbmVzaG9wLmNvbS5ucC91c2VyLWFjY291bnQiLAogICAgICAgICAgICAiaWNvbiI6ICJ1c2VyIgogICAgICAgIH0KICAgIF0sCgogICAgImZsb2F0aW5nQnV0dG9uIjogMSwKICAgICJmbG9hdGluZ0ljb24iOiAid2VjaGF0IiwKICAgICJmbG9hdGluZ0NsaWNrIjogImh0dHBzOi8vd2EubWUvOTc3OTgwNDI5MjIwMiIKCn0=" | base64 -d > assets/flutter_assets/assets/config.json

      - name: Show config.json contents (for debug)
        run: cat assets/flutter_assets/assets/config.json


      # 5. Rebuild APK
      - name: Rebuild APK
        run: |
          apktool b . -o unsigned.apk

      # 6. Zipalign
      - name: Zipalign APK
        run: |
          zipalign -p -f 4 unsigned.apk aligned.apk

      # 7. Decode Keystore from base64 secret
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > appvly.jks

      # 8. Sign APK using provided secrets
      - name: Sign APK
        run: |
          apksigner sign \
            --ks appvly.jks \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASS }} \
            --key-pass pass:${{ secrets.KEY_PASS }} \
            --out final.apk \
            aligned.apk

      # 9. Verify signature
      - name: Verify APK Signature
        run: |
          apksigner verify final.apk

      # 10. Upload signed APK
      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: signed_appvly_apk
          path: final.apk
